version: '3'
services:
  server:
    labels:
      jazy.minecraft.server.description: "Spigot minecraft server"
    image: jazy5552/minecraft-server:latest
    networks:
      - minecraft
    volumes:
      - minecraft-data:/minecraft
    deploy:
      restart_policy:
        delay: 10m
        max_attempts: 10

networks:
  minecraft:
    external:
      name: "host"

volumes:
  minecraft-data:

